### PR TITLE
added alifiroozidev.md

### PR DESCRIPTION
**Pull request by alifiroozidev**

### CODE REVIEW

**Comment by BaseMax** [comment]
Hi there, welcome to the community.
you have to remove all the comments. such as ` <!-- LEAVE EMPTY OR PUT LINK TO YOUR PROFILE -->`

**Review by alifiroozidev — COMMENTED** [review]
updated

**Comment by BaseMax** [comment]
LGTM, Welcome.
thanks

**Review by BaseMax — APPROVED** [review]
lgtm

**Comment by BaseMax** [comment]
> sorry, seems I didn't join!
> 
> > lgtm

Welcome

**Pull request merged**
