### PR TITLE
Create mauro-balades.md

### PR DESCRIPTION
**Pull request by maurobalades-contributions**

### CODE REVIEW

**Comment by BaseMax** [comment]
Welcome.

**Review by BaseMax — APPROVED** [review]
It's OK. (But Need to remove comments)

**Comment by BaseMax** [comment]
You are welcome to do the same for https://github.com/POSSF/POSSF#do-you-want-to-support-so-add-yourself too.
@maurobalades-contributions

Welcome, Thanks in advance.

**Comment by mauro-balades** [comment]
Sure.

**Pull request merged**
