### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by ayushrana182**
Made a minor change to my details. Please merge this!

### CODE REVIEW

**Comment by BaseMax** [comment]
Thanks

**Comment by BaseMax** [comment]
Thanks l you, welcome. 👌😀

**Review by BaseMax — DISMISSED** [review]
Welcome 🤗

**Comment by BaseMax** [comment]
It has conflicts?

**Comment by ayushrana182** [comment]
No Sir, I needed to change some details in my description. Hey MAX, if you know who's working on the One Website I'd like to hop on and contribute.

**Comment by BaseMax** [comment]
You no longer are a DevOps and Linux lover?

**Comment by BaseMax** [comment]
About the **One**, please DM me on Discord tomorrow.
The new UI is ready and, a designer did some work on that UI.

**Comment by ayushrana182** [comment]
I am a lover but I don't have that much experience to put it as expertise. Sure, will do Max.

**Pull request merged**
